export const countryCodes = [
    { code: "+376", country: "AD", flag: "🇦🇩" },
    { code: "+971", country: "AE", flag: "🇦🇪" },
    { code: "+93", country: "AF", flag: "🇦🇫" },
    { code: "+1-268", country: "AG", flag: "🇦🇬" },
    { code: "+1-264", country: "AI", flag: "🇦🇮" },
    { code: "+355", country: "AL", flag: "🇦🇱" },
    { code: "+374", country: "AM", flag: "🇦🇲" },
    { code: "+244", country: "AO", flag: "🇦🇴" },
    { code: "+54", country: "AR", flag: "🇦🇷" },
    { code: "+1-684", country: "AS", flag: "🇦🇸" },
    { code: "+43", country: "AT", flag: "🇦🇹" },
    { code: "+61", country: "AU", flag: "🇦🇺" },
    { code: "+297", country: "AW", flag: "🇦🇼" },
    { code: "+994", country: "AZ", flag: "🇦🇿" },
    { code: "+387", country: "BA", flag: "🇧🇦" },
    { code: "+1-246", country: "BB", flag: "🇧🇧" },
    { code: "+880", country: "BD", flag: "🇧🇩" },
    { code: "+32", country: "BE", flag: "🇧🇪" },
    { code: "+226", country: "BF", flag: "🇧🇫" },
    { code: "+359", country: "BG", flag: "🇧🇬" },
    { code: "+973", country: "BH", flag: "🇧🇭" },
    { code: "+257", country: "BI", flag: "🇧🇮" },
    { code: "+229", country: "BJ", flag: "🇧🇯" },
    { code: "+1-441", country: "BM", flag: "🇧🇲" },
    { code: "+673", country: "BN", flag: "🇧🇳" },
    { code: "+591", country: "BO", flag: "🇧🇴" },
    { code: "+55", country: "BR", flag: "🇧🇷" },
    { code: "+1-242", country: "BS", flag: "🇧🇸" },
    { code: "+975", country: "BT", flag: "🇧🇹" },
    { code: "+267", country: "BW", flag: "🇧🇼" },
    { code: "+375", country: "BY", flag: "🇧🇾" },
    { code: "+501", country: "BZ", flag: "🇧🇿" },
    { code: "+1", country: "CA", flag: "🇨🇦" },
    { code: "+236", country: "CF", flag: "🇨🇫" },
    { code: "+242", country: "CG", flag: "🇨🇬" },
    { code: "+41", country: "CH", flag: "🇨🇭" },
    { code: "+56", country: "CL", flag: "🇨🇱" },
    { code: "+237", country: "CM", flag: "🇨🇲" },
    { code: "+86", country: "CN", flag: "🇨🇳" },
    { code: "+57", country: "CO", flag: "🇨🇴" },
    { code: "+506", country: "CR", flag: "🇨🇷" },
    { code: "+53", country: "CU", flag: "🇨🇺" },
    { code: "+238", country: "CV", flag: "🇨🇻" },
    { code: "+357", country: "CY", flag: "🇨🇾" },
    { code: "+420", country: "CZ", flag: "🇨🇿" },
    { code: "+49", country: "DE", flag: "🇩🇪" },
    { code: "+253", country: "DJ", flag: "🇩🇯" },
    { code: "+45", country: "DK", flag: "🇩🇰" },
    { code: "+1-767", country: "DM", flag: "🇩🇲" },
    { code: "+1-809", country: "DO", flag: "🇩🇴" },
    { code: "+213", country: "DZ", flag: "🇩🇿" },
    { code: "+593", country: "EC", flag: "🇪🇨" },
    { code: "+372", country: "EE", flag: "🇪🇪" },
    { code: "+20", country: "EG", flag: "🇪🇬" },
    { code: "+291", country: "ER", flag: "🇪🇷" },
    { code: "+34", country: "ES", flag: "🇪🇸" },
    { code: "+251", country: "ET", flag: "🇪🇹" },
    { code: "+358", country: "FI", flag: "🇫🇮" },
    { code: "+679", country: "FJ", flag: "🇫🇯" },
    { code: "+33", country: "FR", flag: "🇫🇷" },
    { code: "+241", country: "GA", flag: "🇬🇦" },
    { code: "+44", country: "GB", flag: "🇬🇧" },
    { code: "+1-473", country: "GD", flag: "🇬🇩" },
    { code: "+995", country: "GE", flag: "🇬🇪" },
    { code: "+233", country: "GH", flag: "🇬🇭" },
    { code: "+220", country: "GM", flag: "🇬🇲" },
    { code: "+224", country: "GN", flag: "🇬🇳" },
    { code: "+240", country: "GQ", flag: "🇬🇶" },
    { code: "+30", country: "GR", flag: "🇬🇷" },
    { code: "+502", country: "GT", flag: "🇬🇹" },
    { code: "+245", country: "GW", flag: "🇬🇼" },
    { code: "+592", country: "GY", flag: "🇬🇾" },
    { code: "+504", country: "HN", flag: "🇭🇳" },
    { code: "+385", country: "HR", flag: "🇭🇷" },
    { code: "+509", country: "HT", flag: "🇭🇹" },
    { code: "+36", country: "HU", flag: "🇭🇺" },
    { code: "+62", country: "ID", flag: "🇮🇩" },
    { code: "+353", country: "IE", flag: "🇮🇪" },
    { code: "+972", country: "IL", flag: "🇮🇱" },
    { code: "+91", country: "IN", flag: "🇮🇳" },
    { code: "+964", country: "IQ", flag: "🇮🇶" },
    { code: "+98", country: "IR", flag: "🇮🇷" },
    { code: "+354", country: "IS", flag: "🇮🇸" },
    { code: "+39", country: "IT", flag: "🇮🇹" },
    { code: "+1-876", country: "JM", flag: "🇯🇲" },
    { code: "+962", country: "JO", flag: "🇯🇴" },
    { code: "+81", country: "JP", flag: "🇯🇵" },
    { code: "+254", country: "KE", flag: "🇰🇪" },
    { code: "+996", country: "KG", flag: "🇰🇬" },
    { code: "+855", country: "KH", flag: "🇰🇭" },
    { code: "+686", country: "KI", flag: "🇰🇮" },
    { code: "+269", country: "KM", flag: "🇰🇲" },
    { code: "+82", country: "KR", flag: "🇰🇷" },
    { code: "+965", country: "KW", flag: "🇰🇼" },
    { code: "+7", country: "KZ", flag: "🇰🇿" },
    { code: "+856", country: "LA", flag: "🇱🇦" },
    { code: "+961", country: "LB", flag: "🇱🇧" },
    { code: "+423", country: "LI", flag: "🇱🇮" },
    { code: "+94", country: "LK", flag: "🇱🇰" },
    { code: "+231", country: "LR", flag: "🇱🇷" },
    { code: "+266", country: "LS", flag: "🇱🇸" },
    { code: "+370", country: "LT", flag: "🇱🇹" },
    { code: "+352", country: "LU", flag: "🇱🇺" },
    { code: "+371", country: "LV", flag: "🇱🇻" },
    { code: "+218", country: "LY", flag: "🇱🇾" },
    { code: "+212", country: "MA", flag: "🇲🇦" },
    { code: "+377", country: "MC", flag: "🇲🇨" },
    { code: "+373", country: "MD", flag: "🇲🇩" },
    { code: "+382", country: "ME", flag: "🇲🇪" },
    { code: "+261", country: "MG", flag: "🇲🇬" },
    { code: "+692", country: "MH", flag: "🇲🇭" },
    { code: "+223", country: "ML", flag: "🇲🇱" },
    { code: "+95", country: "MM", flag: "🇲🇲" },
    { code: "+976", country: "MN", flag: "🇲🇳" },
    { code: "+222", country: "MR", flag: "🇲🇷" },
    { code: "+356", country: "MT", flag: "🇲🇹" },
    { code: "+230", country: "MU", flag: "🇲🇺" },
    { code: "+960", country: "MV", flag: "🇲🇻" },
    { code: "+265", country: "MW", flag: "🇲🇼" },
    { code: "+52", country: "MX", flag: "🇲🇽" },
    { code: "+60", country: "MY", flag: "🇲🇾" },
    { code: "+258", country: "MZ", flag: "🇲🇿" },
    { code: "+264", country: "NA", flag: "🇳🇦" },
    { code: "+227", country: "NE", flag: "🇳🇪" },
    { code: "+234", country: "NG", flag: "🇳🇬" },
    { code: "+505", country: "NI", flag: "🇳🇮" },
    { code: "+31", country: "NL", flag: "🇳🇱" },
    { code: "+47", country: "NO", flag: "🇳🇴" },
    { code: "+977", country: "NP", flag: "🇳🇵" },
    { code: "+64", country: "NZ", flag: "🇳🇿" },
    { code: "+968", country: "OM", flag: "🇴🇲" },
    { code: "+507", country: "PA", flag: "🇵🇦" },
    { code: "+51", country: "PE", flag: "🇵🇪" },
    { code: "+675", country: "PG", flag: "🇵🇬" },
    { code: "+63", country: "PH", flag: "🇵🇭" },
    { code: "+92", country: "PK", flag: "🇵🇰" },
    { code: "+48", country: "PL", flag: "🇵🇱" },
    { code: "+351", country: "PT", flag: "🇵🇹" },
    { code: "+595", country: "PY", flag: "🇵🇾" },
    { code: "+974", country: "QA", flag: "🇶🇦" },
    { code: "+40", country: "RO", flag: "🇷🇴" },
    { code: "+381", country: "RS", flag: "🇷🇸" },
    { code: "+7", country: "RU", flag: "🇷🇺" },
    { code: "+250", country: "RW", flag: "🇷🇼" },
    { code: "+966", country: "SA", flag: "🇸🇦" },
    { code: "+249", country: "SD", flag: "🇸🇩" },
    { code: "+46", country: "SE", flag: "🇸🇪" },
    { code: "+65", country: "SG", flag: "🇸🇬" },
    { code: "+386", country: "SI", flag: "🇸🇮" },
    { code: "+421", country: "SK", flag: "🇸🇰" },
    { code: "+221", country: "SN", flag: "🇸🇳" },
    { code: "+597", country: "SR", flag: "🇸🇷" },
    { code: "+503", country: "SV", flag: "🇸🇻" },
    { code: "+963", country: "SY", flag: "🇸🇾" },
    { code: "+235", country: "TD", flag: "🇹🇩" },
    { code: "+228", country: "TG", flag: "🇹🇬" },
    { code: "+66", country: "TH", flag: "🇹🇭" },
    { code: "+216", country: "TN", flag: "🇹🇳" },
    { code: "+90", country: "TR", flag: "🇹🇷" },
    { code: "+886", country: "TW", flag: "🇹🇼" },
    { code: "+255", country: "TZ", flag: "🇹🇿" },
    { code: "+380", country: "UA", flag: "🇺🇦" },
    { code: "+256", country: "UG", flag: "🇺🇬" },
    { code: "+1", country: "US", flag: "🇺🇸" },
    { code: "+598", country: "UY", flag: "🇺🇾" },
    { code: "+998", country: "UZ", flag: "🇺🇿" },
    { code: "+58", country: "VE", flag: "🇻🇪" },
    { code: "+84", country: "VN", flag: "🇻🇳" },
    { code: "+967", country: "YE", flag: "🇾🇪" },
    { code: "+27", country: "ZA", flag: "🇿🇦" },
    { code: "+260", country: "ZM", flag: "🇿🇲" },
    { code: "+263", country: "ZW", flag: "🇿🇼" },
];

export const timezones = [
    { value: "UTC -12:00 Baker Island", label: "UTC -12:00 Baker Island" },
    { value: "UTC -11:00 Pago Pago", label: "UTC -11:00 Pago Pago" },
    { value: "UTC -10:00 Honolulu", label: "UTC -10:00 Honolulu" },
    { value: "UTC -09:30 Taiohae", label: "UTC -09:30 Taiohae" },
    { value: "UTC -09:00 Anchorage", label: "UTC -09:00 Anchorage" },
    { value: "UTC -08:00 Los Angeles, Vancouver", label: "UTC -08:00 Los Angeles, Vancouver" },
    { value: "UTC -07:00 Denver, Phoenix", label: "UTC -07:00 Denver, Phoenix" },
    { value: "UTC -06:00 Chicago, Mexico City", label: "UTC -06:00 Chicago, Mexico City" },
    { value: "UTC -05:00 New York, Toronto", label: "UTC -05:00 New York, Toronto" },
    { value: "UTC -04:00 Santiago, Caracas", label: "UTC -04:00 Santiago, Caracas" },
    { value: "UTC -03:30 St. Johns", label: "UTC -03:30 St. Johns" },
    { value: "UTC -03:00 São Paulo, Buenos Aires", label: "UTC -03:00 São Paulo, Buenos Aires" },
    { value: "UTC -02:00 South Georgia", label: "UTC -02:00 South Georgia" },
    { value: "UTC -01:00 Azores, Cape Verde", label: "UTC -01:00 Azores, Cape Verde" },
    { value: "UTC +00:00 London, Dublin, Lisbon", label: "UTC +00:00 London, Dublin, Lisbon" },
    { value: "UTC +01:00 Paris, Berlin, Rome", label: "UTC +01:00 Paris, Berlin, Rome" },
    { value: "UTC +02:00 Cairo, Johannesburg", label: "UTC +02:00 Cairo, Johannesburg" },
    { value: "UTC +03:00 Moscow, Nairobi, Riyadh", label: "UTC +03:00 Moscow, Nairobi, Riyadh" },
    { value: "UTC +03:30 Tehran", label: "UTC +03:30 Tehran" },
    { value: "UTC +04:00 Dubai, Baku", label: "UTC +04:00 Dubai, Baku" },
    { value: "UTC +04:30 Kabul", label: "UTC +04:30 Kabul" },
    { value: "UTC +05:00 Karachi, Tashkent", label: "UTC +05:00 Karachi, Tashkent" },
    { value: "UTC +05:30 New Delhi, Mumbai", label: "UTC +05:30 New Delhi, Mumbai" },
    { value: "UTC +05:45 Kathmandu", label: "UTC +05:45 Kathmandu" },
    { value: "UTC +06:00 Dhaka, Almaty", label: "UTC +06:00 Dhaka, Almaty" },
    { value: "UTC +06:30 Yangon", label: "UTC +06:30 Yangon" },
    { value: "UTC +07:00 Bangkok, Jakarta, Hanoi", label: "UTC +07:00 Bangkok, Jakarta, Hanoi" },
    { value: "UTC +08:00 Singapore, Hong Kong, Beijing", label: "UTC +08:00 Singapore, Hong Kong, Beijing" },
    { value: "UTC +08:45 Eucla", label: "UTC +08:45 Eucla" },
    { value: "UTC +09:00 Tokyo, Seoul", label: "UTC +09:00 Tokyo, Seoul" },
    { value: "UTC +09:30 Adelaide, Darwin", label: "UTC +09:30 Adelaide, Darwin" },
    { value: "UTC +10:00 Sydney, Melbourne", label: "UTC +10:00 Sydney, Melbourne" },
    { value: "UTC +10:30 Lord Howe Island", label: "UTC +10:30 Lord Howe Island" },
    { value: "UTC +11:00 Solomon Islands", label: "UTC +11:00 Solomon Islands" },
    { value: "UTC +12:00 Auckland, Fiji", label: "UTC +12:00 Auckland, Fiji" },
    { value: "UTC +12:45 Chatham Islands", label: "UTC +12:45 Chatham Islands" },
    { value: "UTC +13:00 Tonga, Samoa", label: "UTC +13:00 Tonga, Samoa" },
    { value: "UTC +14:00 Line Islands", label: "UTC +14:00 Line Islands" },
];
